-- =========================
-- USERS
-- =========================
CREATE TABLE users (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    password text NOT NULL,
    verify boolean DEFAULT false,
    salt text NOT NULL,
    tokenversion integer DEFAULT 0
);

-- =========================
-- RECIPE
-- =========================
CREATE TABLE recipe (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    title text NOT NULL,
    preptime integer NOT NULL,
    cooktime integer NOT NULL,
    servings integer NOT NULL,
    rating integer,
    ingredients json NOT NULL,
    instructions text NOT NULL,
    seen boolean DEFAULT false NOT NULL,
    checked boolean DEFAULT false NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- =========================
-- FAVORITES
-- =========================
CREATE TABLE favourite_recipe (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    recipeid integer NOT NULL
);

-- =========================
-- RECIPE IMAGES
-- =========================
CREATE TABLE recipe_image (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_id integer NOT NULL,
    image text NOT NULL
);

-- =========================
-- EMAIL CHANGE
-- =========================
CREATE TABLE emailchange (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    userid integer NOT NULL,
    token text NOT NULL,
    email text NOT NULL
);
